[versions]
kotlin = "2.2.20"
spring-boot = "3.5.4"
spring-framework = "6.1.6"
spring-management = "1.1.7"
springData = "3.5.2"
jackson = "2.17.2"
flyway = "10.15.0"
postgresql = "42.7.4"
aws-sdk = "2.32.24"
coroutines-core = "1.10.1"
project-reactor-kotlin = "1.2.3"
reactorNetty = "1.1.22"

[libraries]
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }

flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }

postgresql-driver = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j", version = "9.1.0" }

spring-boot-starter-webflux = { module="org.springframework.boot:spring-boot-starter-webflux", version.ref = "spring-boot" }
aws-v2-netty = { module="software.amazon.awssdk:netty-nio-client", version.ref="aws-sdk"}

common-coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-core" }
kotlinx-coroutines-reactor = { module="org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines-core" }

reactor-kotlin-extensions = { module="io.projectreactor.kotlin:reactor-kotlin-extensions", version.ref = "project-reactor-kotlin" }
spring-webflux = { module = "org.springframework:spring-webflux", version.ref = "spring-framework" }
reactor-netty-http = { module = "io.projectreactor.netty:reactor-netty-http", version.ref = "reactorNetty" }

spring-data-jpa = { module = "org.springframework.data:spring-data-jpa", version.ref = "springData" }
jakarta-persistence = { module = "jakarta.persistence:jakarta.persistence-api", version = "3.1.0" }
spring-orm = { module = "org.springframework:spring-orm", version.ref = "spring-framework" }
spring-tx  = { module = "org.springframework:spring-tx",  version.ref = "spring-framework" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
springboot = { id = "org.springframework.boot", version.ref = "spring-boot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-management" }